on:
  workflow_dispatch:

jobs:
  my_job:
    name: build-test
    runs-on: macos-13
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '1.23.2'
    - name: set up
      run: go install golang.org/x/mobile/cmd/gomobile@latest
    - name: test
      run: gomobile init
    - name: build
      run: sh ./fetch-web.sh
    - name: build real
      run: gomobile bind -target ios -bundleid {test.alist.ios} -o /ios/alist/Alistlib.xcframework -ldflags "-s -w" github.com/alist-org/alist/v3/alistlib
