on:
  workflow_dispatch:

jobs:
  my_job:
    name: build-test
    runs-on: macos-13
    
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5.1.0
    - name: set up
      run: go install golang.org/x/mobile/cmd/gomobile@latest
    - name: test
      run: gomobile init
